version: ci-{build}-{branch}
image: Visual Studio 2019
configuration: Release
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: GitHub
  auth_token:
    secure: eHI+nPFCmnPOdRRPRhGQBso/RlA5seuhkPBRgOMbGWDHzNWw+Us1FJrR7TTBLVR0
  on:
    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: YDqMLmNrdBgJpslJ6AfFf25Kt6OSblR5I6cWcTARVCDkWLr7VhYPC7BAw2iK1oU5
  on:
    appveyor_repo_tag: true
